# Generated by Django 4.2.7 on 2023-12-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=400)),
                ('company', models.CharField(max_length=100)),
                ('postes_on', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('Rulesresponsibilities', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('post_type', models.CharField(max_length=100)),
                ('post_title', models.CharField(blank=True, max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('img', models.ImageField(blank=True, upload_to='userimage/')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('jobtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobposts', to='jobpostapp.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='jobpostapp.post')),
            ],
        ),
    ]
